### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by apiszcz** [JaidedAI/EasyOCR#115]
If multiple languages are passed fin for detection ['a', 'b', 'c']
Is it possible to get the detected language type returned in the the readtext response?

**Comment by rkcosmos** [comment]
Not quite understand. Do you want a feature for detecting language?

**Comment by apiszcz** [comment]
Sorry, probably my lack of understanding. When initializing easyocr a list of languages are supplied
reader = easyocr.Reader(['sk','en'])
The result set provides the bounding box, UNICODE text and score. I am wondering if there are multiple languages specified in the constructor if the language used for the detection record should be in the result.


NOW:
bounding box, UNICODE text, score

MAYBE?
bounding box, UNICODE text, score, language (e.g. 'en')

Language detection should not be required since we now what detector is being applied to the image (I think).

Thanks.

**Comment by rkcosmos** [comment]
Sure, it's easily doable by checking UNICODE text against characters in each language. I will add 'PR WELCOME' tag to this and wait for coder who want to contribute.

**Comment by apiszcz** [comment]
chardet may be related.

https://pypi.org/project/chardet/

**Comment by Biswasahu7** [comment]
When it reading from image every time it is reading 1 to i else |. Please advice how we can improve it

**Comment by arkya-art** [comment]
Can I take up this issue and work on it? @rkcosmos can you guide me if possible for this

**Comment by roccopietrini** [comment]
Why has been marked has solved? There are several issues like #683 and this #572 . The function simply does not work because it looks for txt files in a folder (hardcoded) named `characters`. Who is in charge of creating those txt files and what sould they contain?

I made a small colab [here](https://colab.research.google.com/drive/1BwumRgVht6hkujrs9dAy03T6B32KTqjS?usp=sharing)

In addition.. looking at the code it looks like it's only able to deal with chinese and english.. maybe we can just polyglot for that ? It works pretty wel..
