### ISSUE TITLE
Question about dict

### ISSUE THREAD

**Issue by 2juhyun** [JaidedAI/EasyOCR#127]
I have to wondering about dict file's purpose.

I think it is not used to predict.

What is purpose of dict files? It used at training time?

**Comment by rkcosmos** [comment]
training time and wordbeamsearch decoder. will also used in advanced decoder later

**Comment by amitbcp** [comment]
@rkcosmos what are your thought/ideas for the advanced decoder ?

Currently I was thinking of adding some OOV words in the dict so that the recognition of the words improves.  
But on adding it , it did not help in any such way. 
Any thoughts on how can we update the dictionary to improve recognition for specific technical words ?
