### ISSUE TITLE
Question regarding beam search decoder implementation

### ISSUE THREAD

**Issue by nobodykid** [JaidedAI/EasyOCR#215]
Hi, I'm currently working on a beam search decoder for my project and inspired from your code. But I have question regarding it, after did a bit of comparison with the original implementation

- I see you put [different value](https://github.com/JaidedAI/EasyOCR/blob/master/easyocr/utils.py#L140) on `blankIdx` inside `ctcBeamSearch` function compared to the original implementation at [here](https://github.com/githubharald/CTCDecoder/blob/master/src/BeamSearch.py#L55). Was this to accommodate different position for blank character in your model output?
-  Also inside `ctcBeamSearch` function, I see the difference during extending the beam. On your code, it seems you filter all characters to most probable one and then iterates over it, while the original iterates over all characters instead. What's the reason behind the change? And what's the logic behind the condition `mat[t, :] >= 0.5/maxC`?

Thank you

**Comment by rkcosmos** [comment]
1. My `blankIdx` from pytorch model is at the first position, so I change accordingly.
2. I put that condition to keep only the probable trees to the next iteration. Tree with very low score is unlikely to be the solution anyway. Without this condition, size of search tree will be extremely large for long sequence and consume too much resource for practical use.

**Comment by nobodykid** [comment]
Aah I thought so, since compared to original it took shorter time.

But it seems affecting the decoding result a bit. I did test run with the sample from the original repo (not using the language model) and it comes with this result
```
=====Line example=====      
TARGET  			: "the fake friend of the family, like the"
BEST PATH       		: "the fak friend of the fomly hae tC"  	CER/WER: 0.26471/0.15254
BEAM SEARCH     		: "the fak friend of the fomcly hae tC"         CER/WER: 0.25714/0.15000
BEAM SEARCH - EASYOCR   	: "th fak friend of he fomly hae tC"    	CER/WER: 0.34375/0.19298
```
Any idea on how we can keep the prediction good while still faster on decoding time?

**Comment by rkcosmos** [comment]
Comparison is always welcome, can you do it with bigger data? I think one line isn't conclusive. Also make sure this is done with the same beamWidth.

There's also another factor. The training process in EasyOCR is done with dictionary, that means recognition model already learn not only to predict each character but taking into account the surrounding context as well. Because of this, using beamsearch/wordbeamsearch in EasyOCR may not boost the performance by large margin.  

To keep good performance (in general case), you may try to play with threshold `mat[t, :] >= ths/maxC`. Now `ths=0.5`, you can just lower it until you find the best trade-off for your application. 

I believe there must be a better solution though than just tuning `ths` though.
