### ISSUE TITLE
Replace Detector backbone to MobileNet or EfficientNet ?

### ISSUE THREAD

**Issue by SungmanHong** [JaidedAI/EasyOCR#242]
1. Is it possible to retrain CRAFT based on a lighter MobileNet or EfficientNet backbone ?

2. Is it possible to convert TFlite model to do real-time OCR in android?

**Comment by rkcosmos** [comment]
1. we are not going to retrain CRAFT (detection part) because the bottleneck is in recognition part. We intend to retrain recognition part with lighter network for lite version model. It's going to be faster but most probably less accurate. 
2. we don't officially support conversion to other platform yet. I think it's possible to export to ONNX and from there, to platform of your choice. I've not done it myself though.

**Comment by huzaifah-here** [comment]
@SungmanHong did you successfully export it from ONNX?
