### ISSUE TITLE
Why using width_ths*height_box in group text box

### ISSUE THREAD

**Issue by z-pc** [JaidedAI/EasyOCR#350]
Sorry, this is not issue, I'm just wondering.
When using "width_ths" to group text box, I see it is multiplied with "height_box" and compare with distance between two boxes.
I thought it should be multiplied by "width_box", right?
I experimented with this, it gives much better results.

**Comment by rkcosmos** [comment]
Multiplication with `height_box` is intentional. The idea is `height_box` is an approximation of character size. The decision to merge text box is calculated from `width_ths*height_box`. If `width_ths` = 2, then we merge the boxes when the distance is less than 2 characters (approximately). `width_box` depends on length of word in consideration, if a word is very long, we may end up merging very far boxes together.

**Comment by z-pc** [comment]
Yep
I tried again with a long word, width_box is harder to control than height_box.
Thanks !
