### ISSUE TITLE
deep-text-recognition-benchmark usage

### ISSUE THREAD

**Issue by burak-yildizoz** [JaidedAI/EasyOCR#392]
This is not an issue but rather a guide to test or train EasyOCR.
---

I have seen many issues about testing the model with [deep-text-recognition-benchmark](https://github.com/clovaai/deep-text-recognition-benchmark). So, here is the command for a quick demo. Any suggestion is welcome.

```
python3 demo.py --image_folder /path/to/images/folder/ \
--saved_model ~/.EasyOCR/model/latin.pth \
--Transformation None \
--FeatureExtraction ResNet \
--SequenceModeling BiLSTM \
--Prediction CTC \
--hidden_size 512 \
--character "$(cat characters.txt)"
```
where `characters.txt` contains
```
0123456789!"#$%&'()*+,-./:;<=>?@[\]^_`{|}~ ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyzÀÁÂÃÄÅÆÇÈÉÊËÍÎÑÒÓÔÕÖØÚÛÜÝÞßàáâãäåæçèéêëìíîïðñòóôõöøùúûüýþÿąęĮįıŁłŒœŠšųŽž
```
See [model language](https://github.com/JaidedAI/EasyOCR/blob/cdef0b4ae3109b72e4610706089f17a457e576dc/easyocr/easyocr.py#L145) and `easyocr/config.py` for characters of other models.

**Comment by burak-yildizoz** [comment]
Model information is mentioned [in this comment](https://github.com/JaidedAI/EasyOCR/issues/365#issuecomment-789957678).

**Comment by mjack3** [comment]
Hello @burak-yildizoz  thanks you for ur response. In my proyect, I just need to detect numbers and one special character.
`0123456789-`

In deep-text-recognition-benchmark I have trained with a custom dictionary which is 
`0123456789-`

What changes should i do in EasyOCR to just use that characters? i am really frustrated because the easyOCR show (like) random results in the recognition task whearas deep-text-recognition-benchmark give me really good results

**Comment by burak-yildizoz** [comment]
@mjack3 I don't know any such option but I am not an expert either. If your model is working, you can try training it with more dataset for further improvement in results instead of using the model provided by EasyOCR, or you can open a new issue about that.
