### ISSUE TITLE
After the version 1.4 update, the speed of detection has been slowed down.

### ISSUE THREAD

**Issue by ai-motive** [JaidedAI/EasyOCR#474]
It is much slower than the previous code for high-resolution image(ex : 967x3542) processing.

In my opinion, the problem arises with matrix arithmetic multiplication of text detection. (in test_net() method)

**Text detection processing time comparison**
 - prev. code (v1.3.2) : 0.2 sec
 - curr. code (v1.4) : 4.0 sec

plz review this comment

Best regards

**Comment by SamSamhuns** [comment]
Did you try timing the different parts of the detection method separately? Which code section specifically is causing the slowdown (inside the `test_net()` method)

**Comment by samayala22** [comment]
I've profiled both functions with line_profiler and have seen no differences in speed.

**Comment by fann1993814** [comment]
Please try to set OMP_NUM_THREADS=1?

**Comment by vneseresearcher** [comment]
@SamSamhuns I also had the same problem. I tried with original source code and installed via pip. Tested on 2 different PCs. 

After measuring the time of each piece of code, I found the following code to be time consuming
score_text = out[:, :, 0].cpu().data.numpy()
score_link = out[:, :, 1].cpu().data.numpy()
(line 50,51 in detection.py - test_net)

I checked the cpu and it only used 1 core.
And then I use raw CRAFT, it is faster (same code)

**Comment by vneseresearcher** [comment]
> Please try to set OMP_NUM_THREADS=1?

I did it but nothing changed about speed.

**Comment by SamSamhuns** [comment]
@vneseresearcher, what is the test code that you are using to measure the time? I do not see any significant difference in CPU inference time after trying the 1.3.2 and the 1.4.0 release

**Comment by SamSamhuns** [comment]
Thanks for bringing this up again guys 

So I ran a few tests between releases 1.3.2 and 1.4, in CPU mode there is not much of a difference in inference speed.
However, in GPU mode I did see a significant slowdown in inference speed for release 1.4.

As @vneseresearcher pointed out, using normal time profiling, this section stands out to be the most time-consuming in the new release. 
```python
score_text = out[:, :, 0].cpu().data.numpy()
score_link = out[:, :, 1].cpu().data.numpy()
```
However, this might not be the culprit because calling `.cpu()` creates a synchronization point for CUDA operations that run asynchronously. This means before the data can be transferred to memory, all current and queued operations on the GPU must be finished first, so the program is doing a wait operation with the `.cpu()` call. I did some debugging and comparing the previous `test_net()` function, I localized the issue to the preprocessing section.

So I rewrote the preprocessing implementation and now the `test_net()` function call should not be slow anymore. I will create a PR for this later, but if you guys want to test it out right now, just do the following replacement in `easyocr/detection.py`

From line 38 to 41
```python
# preprocessing
x = np.array([normalizeMeanVariance(n_img) for n_img in img_resized_list])
x = Variable(torch.from_numpy(x).permute(0, 3, 1, 2))  # [b,h,w,c] to [b,c,h,w]
x = x.to(device)
```

to 

```python
# preprocessing
x = [np.transpose(normalizeMeanVariance(n_img), (2, 0, 1))
     for n_img in img_resized_list]
x = torch.from_numpy(np.array(x))
x = x.to(device)
```

@vneseresearcher @ai-motive, let me know if guys can get similar speeds to release 1.3.2 on the GPU with this new replacement

**Comment by vneseresearcher** [comment]
@SamSamhuns Great. Speed has improved. Thanks a lot!

**Comment by purplesword** [comment]
Thank you for the fix! 

@rkcosmos will there be a 1.4.1 release with the fix soon? Thank you.
