### ISSUE TITLE
Use opencv-python-headless as dependency

### ISSUE THREAD

**Issue by timurlenk07** [JaidedAI/EasyOCR#485]
Hi! If no GUI functions are used from *opencv-python* then the dependency could be changed to *opencv-python-headless* instead, so there would be no errors in Docker containers lacking GUI libraries when importing cv2 like the following: 

> ImportError: libGL.so.1: cannot open shared object file: No such file or directory

**Comment by bertsky** [comment]
I second that. For headless deployments, `opencv-python` does not work, as it drags in X11 libraries. I would suggest making `opencv-python-headless` the default, since AFAICS EasyOCR does not (yet?) have any GUI/plotting facilities. 

(And if it does, one could encapsulate them under an `extras_require` section in setup.py, making these features installable via `pip install easyocr[plotting]` or something like this...)
