### ISSUE TITLE
Finding leading punctuation

### ISSUE THREAD

**Issue by csterritt** [JaidedAI/EasyOCR#63]
Hello,

Thanks for doing this! It looks very good.

I ran this on some text that I'd like to covert, which has lines like this, which includes embedded markdown:

~~~
===== Header
----- Section
     example text
     ~~~ js
            x = foo(y, z)
     ~~~
~~~

The problem is that the leading punctuation, such as the "=====" in the first line, are just ignored entirely.  Later punctuation seems to be found with no problem.

Is there a way to have the algorithm find these as well?

**Comment by rkcosmos** [comment]
OCR process involves detection and recognition. In your case, it is detection part that ignore "=====" because it thinks this is not text which is quite subjective to judge even for human. To solve your problem, it may help to change parameter for detection part here

https://github.com/JaidedAI/EasyOCR/blob/fdb861109aab9724ae3bdbf67ec4b1222adcd5f3/easyocr/easyocr.py#L19-L24

**Comment by csterritt** [comment]
Thanks @rkcosmos I'll try that out.
