### ISSUE TITLE
Unable to install easyocr, says pillow version is 8.2.0 however my installed version is 9.0.1

### ISSUE THREAD

**Issue by goodbobonlone** [JaidedAI/EasyOCR#685]
Hi, I am having trouble installing easyOCR, are there more dependencies I need other than PyTorch and Pillow?  How can I fix this?
Attached is what my cmd returned when I used "pip install easyocr"

![Error1](https://user-images.githubusercontent.com/14850652/158920603-2e210bd9-672a-4ad6-98d0-55ecfb6e5799.png)
![Error2](https://user-images.githubusercontent.com/14850652/158920608-821ad2ab-2bb1-4606-b36c-2e449d88bda7.png)

**Comment by goodbobonlone** [comment]
If you would like any additional information on this I can provide it.

**Comment by SatyamSSJ10** [comment]
what is your python version? I'd suggest using 3.8.x because this version is best suitable for EasyOCR.

**Comment by goodbobonlone** [comment]
I'm using python 3.10.3

**Comment by anylanes** [comment]
there was a similar problem. When I figured it out, I realized that the maximum version of python that can work with easyocr is 3.9, since this library uses pillow version 8.2.0. I use Pycharm and there, when creating a new project, I also clicked these two boxes, and only after that the library was installed no1rmall.
<img width="793" alt="1" src="https://user-images.githubusercontent.com/101903547/159082029-43a44fc8-ef7c-447d-95ab-0a31dbd55098.png">

**Comment by goodbobonlone** [comment]
thanks for the info, do you know if there is a way to get 8.2.0 and 3.10 to work together?

**Comment by SatyamSSJ10** [comment]
> thanks for the info, do you know if there is a way to get 8.2.0 and 3.10 to work together?

No, probably Torch isn't compatible with 3.10.x so can't

**Comment by SatyamSSJ10** [comment]
Also you should close the issue
