### ISSUE TITLE
Benchmarking with SOTA approaches

### ISSUE THREAD

**Issue by rameshjesswani** [JaidedAI/EasyOCR#94]
Thanks for sharing this amazing tool.

Did you guys already benchmarked it with other state-of-the-art approaches (e.g. Tesseract)?

**Comment by rkcosmos** [comment]
It's quite hard to compare because there are many different situations in OCR. As far as I know, no open-source OCR can solve all use case in the same package. For scene-text image (like on street, not dense text in document), I'm pretty sure we are better than Tesseract. For dense text (like a pages on book), Tesseract may have upper edge. They are also faster if you don't have GPU.

**Comment by rameshjesswani** [comment]
Cool. thanks for your information. I am closing this issue :)
